### ISSUE TITLE
Files on page are missing in distribution - REBUILD FIRMWARE - RPi.

### ISSUE THREAD

**Issue by MMaciocia** [robdobsn/BusRaider#7]
The files mentioned on:
https://github.com/robdobsn/BusRaider/wiki/Rebuilding-Pi-Firmware
do not exist in the GIT distribution and the process described cannot be carried out.
Can the instructions be updated please?
regards
Michael

**Comment by robdobsn** [comment]
Apologies, I had gotten ahead of myself and written documentation to build the next iteration of firmware (that I'm working on in my spare time) and hadn't realised that there was no equivalent for the current version. Hopefully the instructions are now correct.
