### ISSUE TITLE
same issue on esp32 build

### ISSUE THREAD

**Issue by MMaciocia** [robdobsn/BusRaider#8]
as per comment on RPi, no matching files for these build instructions

https://github.com/robdobsn/BusRaider/wiki/Rebuilding-ESP32-Firmware

**Comment by robdobsn** [comment]
Apologies, I had gotten ahead of myself and written documentation to build the next iteration of firmware (that I'm working on in my spare time) and hadn't realised that there was no equivalent for the current version. Hopefully the instructions are now correct.
